// A list of fake podcasts

export default [
    "Beyond Mars (1 hr 15 min): Join space enthusiasts as they speculate about extraterrestrial life and the mysteries of distant planets.",
    "Jazz Under Stars (55 min): Experience a captivating night in New Orleans, where jazz melodies echo under the moonlit sky.",
    "Tech Tomorrow (45 min): Exploring cutting-edge innovations and their impact on our daily lives with industry experts.",
    "Bedtime Stories for Kids (25 min): Magical tales featuring dragons, unicorns, and friendly monsters perfect for young listeners.",
    "History's Hidden Gems (1 hr 30 min): Uncovering fascinating historical events that rarely make it into textbooks.",
    "Mindful Mornings (20 min): Start your day with guided meditation and mindfulness exercises for inner peace.",
    "True Crime Chronicles (1 hr): Investigative journalists dive deep into unsolved mysteries and cold cases.",
    "Cooking Without Borders (40 min): Travel the world through traditional recipes and cultural food stories.",
    "Startup Success Stories (50 min): Entrepreneurs share their journey from garage projects to million-dollar companies.",
    "Science for Teens (35 min): Making complex scientific concepts fun and accessible for young minds.",
    "Football Frenzy (1 hr): Weekly analysis of major league games, transfers, and behind-the-scenes drama.",
    "Parent's Guide (45 min): Expert advice on navigating modern parenting challenges and child development.",
    "Environmental Edge (1 hr): Discussing climate change solutions and sustainable living practices.",
    "Digital Artists' Corner (35 min): Tips and techniques for creating stunning digital art and animations.",
    "Money Matters (45 min): Personal finance advice for millennials navigating debt, investments, and savings.",
    "Horror Hour (1 hr): Spine-chilling ghost stories and supernatural encounters narrated by master storytellers.",
    "Fitness Focus (30 min): Quick workout tips and health advice for busy professionals.",
    "Gaming Galaxy (1 hr 20 min): Reviews, strategies, and news from the world of video games.",
    "Pet Paradise (40 min): Veterinarians answer common pet care questions and share heartwarming animal stories.",
    "Language Learning (25 min): Fun and effective methods to master a new language.",
    "Women in Leadership (1 hr): Inspiring stories of female executives breaking barriers in various industries.",
    "DIY Workshop (45 min): Step-by-step guides for home improvement and craft projects.",
    "Mental Health Matters (50 min): Therapists discuss common mental health issues and coping strategies.",
    "Comedy Central (35 min): Stand-up comedians share their funniest moments and behind-the-scenes stories.",
    "Book Club Buzz (1 hr): In-depth discussions about contemporary and classic literature.",
    "Rock Legends (1 hr 30 min): The untold stories behind famous rock bands and their iconic songs.",
    "Future of Work (45 min): Exploring remote work trends and evolving workplace dynamics.",
    "Travel Tales (1 hr): Adventure seekers share their experiences from off-the-beaten-path destinations.",
    "Science of Sleep (30 min): Research-based advice for better sleep and understanding dreams.",
    "Fashion Forward (40 min): Trending styles, sustainable fashion, and industry insights.",
    "Sports Medicine (50 min): Medical professionals discuss common athletic injuries and prevention.",
    "Crypto Talk (45 min): Understanding cryptocurrency, blockchain, and the future of digital finance.",
    "Movie Magic (1 hr): Film critics review latest releases and discuss cinema history.",
    "Garden Guru (35 min): Tips for growing your own food and creating beautiful outdoor spaces.",
    "Ancient Mysteries (1 hr 15 min): Archaeological discoveries and unsolved historical puzzles.",
    "Teen Talk (30 min): Addressing social issues and challenges faced by today's teenagers.",
    "Chess Champions (45 min): Strategic insights and famous matches analyzed by grandmasters.",
    "Weather Watch (25 min): Understanding extreme weather phenomena and climate patterns.",
    "Relationship Reality (50 min): Dating advice and relationship wisdom for modern couples.",
    "Art History (1 hr): Stories behind famous artworks and their cultural impact.",
    "Photography Pro (40 min): Technical tips and creative inspiration for photographers.",
    "Political Pulse (1 hr): Balanced discussions about current political events worldwide.",
    "Yoga Journey (30 min): Guided yoga sessions for practitioners of all levels.",
    "Music Theory (45 min): Understanding the building blocks of music composition.",
    "Entrepreneur Hour (1 hr): Small business owners share their challenges and victories.",
    "Nature Notes (35 min): Exploring wildlife conservation and ecosystem preservation.",
    "Dance Diaries (40 min): Learn different dance styles and their cultural origins.",
    "Senior Living (45 min): Health and lifestyle advice for the elderly population.",
    "Social Media Success (50 min): Building your brand and growing your online presence.",
    "Mystery Theater (1 hr): Modern radio drama featuring original mystery stories.",
    "Coding Corner (45 min): Programming tutorials and software development tips.",
    "Wedding Planning (40 min): Expert advice for couples planning their perfect day.",
    "Alternative Health (55 min): Exploring natural remedies and holistic wellness approaches.",
    "Poetry Cafe (30 min): Contemporary poets share and discuss their work.",
    "Real Estate Round-up (45 min): Market trends and property investment strategies.",
    "Film Scoring (1 hr): Composers discuss the art of creating movie soundtracks.",
    "Automotive Talk (50 min): Car maintenance tips and reviews of new vehicles.",
    "Supernatural Science (45 min): Scientific explanations for seemingly paranormal phenomena.",
    "Career Coach (40 min): Professional development advice and job hunting strategies.",
    "Voice Acting (35 min): Tips and techniques for aspiring voice-over artists.",
    "News Digest (25 min): Daily summary of major world events.",
    "Nutrition Know-how (45 min): Evidence-based dietary advice and meal planning tips.",
    "Broadway Backstage (1 hr): Behind-the-scenes stories from theater productions.",
    "Urban Farming (40 min): Growing food in small spaces and community gardens.",
    "Legal Matters (50 min): Lawyers explain common legal issues in simple terms.",
    "Retirement Ready (45 min): Planning for a comfortable and secure retirement.",
    "Writing Workshop (1 hr): Creative writing techniques and publishing advice.",
    "Ocean Explorers (55 min): Marine biologists share underwater discoveries.",
    "Mythology Minutes (40 min): Stories and legends from cultures around the world.",
    "Astronomy Today (1 hr): Latest discoveries and observations from space.",
    "Design Dialogue (45 min): Interior designers share tips for beautiful living spaces.",
    "Coffee Culture (35 min): Everything about coffee from bean selection to brewing.",
    "Memory Masters (40 min): Techniques for improving memory and cognitive function.",
    "Wilderness Survival (1 hr): Essential skills for outdoor adventures and emergencies.",
    "Animation Station (45 min): The art and technology behind animated films.",
    "Debate Club (1 hr): Respectful discussions about controversial topics.",
    "Museum Mysteries (50 min): Stories of stolen artworks and museum artifacts.",
    "Robotics Review (45 min): Latest developments in robotics and automation.",
    "Ethical Living (40 min): Making sustainable and socially responsible choices.",
    "Magic Tricks (30 min): Learn impressive illusions and sleight of hand.",
    "Birth Stories (1 hr): Parents share their unique childbirth experiences.",
    "Fantasy Football (45 min): Strategy tips and player analysis for fantasy leagues.",
    "Documentary Deep Dive (1 hr 15 min): Analyzing impactful documentary films.",
    "Bike Maintenance (40 min): Keep your bicycle in top condition with expert advice.",
    "Vocal Training (35 min): Exercises and tips for improving your singing voice.",
    "Movie Soundtracks (50 min): analyzing the impact of music in famous films.",
    "Philosophy Now (1 hr): Making philosophical concepts relevant to modern life.",
    "Drumming Basics (45 min): Learn rhythm patterns and percussion techniques.",
    "Virtual Reality (55 min): Exploring the latest developments in VR technology.",
    "Bird Watching (40 min): Identifying and understanding different bird species.",
    "Soap Making (35 min): Create your own natural soaps and bath products.",
    "Chess Strategies (45 min): Advanced tactics for improving your chess game.",
    "Vintage Fashion (50 min): Collecting and styling classic fashion pieces.",
    "Origami Art (30 min): Step-by-step paper folding projects for all levels.",
    "Wine Tasting (45 min): Understanding and appreciating different wine varieties.",
    "Cat Behavior (40 min): Understanding and training your feline companions.",
    "Street Photography (50 min): Capturing compelling images in urban environments.",
    "Martial Arts (55 min): Learning self-defense and martial arts philosophy.",
    "3D Printing (45 min): Projects and tips for 3D printing enthusiasts.",
    "Ghost Stories (1 hr): Real people share their encounters with the paranormal.",
    "Beekeeping Basics (40 min): Starting and maintaining your own honey bee colonies.",
    "Classical Music (1 hr): Understanding and appreciating orchestral masterpieces.",
    "Time Management (35 min): Productivity tips for busy professionals.",
    "Knitting Circle (45 min): Patterns and techniques for knitting projects.",
    "Urban Legends (50 min): Investigating famous myths and local legends."
  ];
  